import { readdirSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  PACK,
  SCHEMA_NAMES,
  createValidator,
  loadYaml,
  schemaId,
  validateAgainst,
} from "./index.ts";

const schemaStems = readdirSync(PACK.schemas)
  .filter((f) => f.endsWith(".schema.json"))
  .map((f) => f.replace(".schema.json", ""))
  .sort();

describe("generated names follow the pack", () => {
  /**
   * `SCHEMA_NAMES` is generated by enumerating the pack, so this asserts the
   * generator ran against the current pack rather than a stale copy. It cannot
   * detect a deleted schema — after the generator wipes its output the counts
   * always agree. Deletion is caught by typecheck, because every reference to a
   * removed name stops compiling, and by the manifest reference test.
   */
  it("SCHEMA_NAMES equals the schemas present in the pack", () => {
    expect([...SCHEMA_NAMES]).toEqual(schemaStems);
  });

  it("no generated module survives a schema that no longer exists", () => {
    const generated = readdirSync(
      new URL("./generated/", import.meta.url),
    )
      .filter((f) => f.endsWith(".ts"))
      .filter((f) => !["index.ts", "events.ts", "schema-names.ts"].includes(f))
      .map((f) => f.replace(".ts", ""))
      .sort();
    expect(generated).toEqual(schemaStems);
  });
});

describe("the single JSON Schema validator", () => {
  const ajv = createValidator();

  it("registers every schema name in ajv strict mode", () => {
    for (const name of SCHEMA_NAMES) {
      expect(ajv.getSchema(schemaId(name)), name).toBeTruthy();
    }
  });

  it("accepts the registry bundle", () => {
    expect(validateAgainst(ajv, "registry-bundle", loadYaml(PACK.registryBundle))).toEqual([]);
  });

  it("accepts the propagation matrix", () => {
    expect(validateAgainst(ajv, "propagation-matrix", loadYaml(PACK.propagationMatrix))).toEqual(
      [],
    );
  });

  it("accepts the event registry", () => {
    expect(validateAgainst(ajv, "event-registry", loadYaml(PACK.eventRegistry))).toEqual([]);
  });

  it("rejects a document that violates its schema", () => {
    expect(validateAgainst(ajv, "registry-bundle", { apiVersion: "wrong" }).length).toBeGreaterThan(
      0,
    );
  });
});
